services:
  postgres:
    build:
      context: ./storage
    environment:
      POSTGRES_PASSWORD: ratings
      POSTGRES_USER: ratings
      POSTGRES_DB: ratings_core
    volumes:
      - postgresdata:/var/lib/postgresql/data
  ratings_core:
    build:
      dockerfile: Dockerfile-core
      context: .
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - 9080:8080
  ratings_webapp:
    build:
      dockerfile: Dockerfile-webapp
      context: .
    depends_on:
      - ratings_core
    restart: on-failure
volumes:
  postgresdata: