services:
  postgres:
    image: nkuznetsov44/ratings_storage:latest
    environment:
      POSTGRES_PASSWORD: ratings
      POSTGRES_USER: ratings
      POSTGRES_DB: ratings_core
    volumes:
      - postgresdata:/var/lib/postgresql/data
  ratings_core:
    image: nkuznetsov44/ratings_core:latest
    pull_policy: always
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - 9080:8080
  ratings_webapp:
    image: nkuznetsov44/ratings_webapp:latest
    pull_policy: always
    depends_on:
      - ratings_core
    restart: on-failure
  nextjs:
    image: artbocha/foosball-fsk-nextjs:latest
    pull_policy: always
    depends_on:
      - ratings_webapp
    environment:
      - WEBAPP_BACKEND_URL=${WEBAPP_BACKEND_URL}
  nginx:
    image: artbocha/foosball-fsk-nginx:latest
    pull_policy: always
    restart: on-failure
    depends_on:
      - ratings_webapp
      - nextjs
    ports:
      - 3000:80
    environment:
      - WEBAPP_BACKEND_URL=${WEBAPP_BACKEND_URL}
volumes:
  postgresdata: