FROM python:3.11-rc-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# psycopg2 deps
RUN apk update && apk add build-base libpq postgresql-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY ./common /opt/ratings/common
COPY ./storage /opt/ratings/storage
COPY ./core /opt/ratings/core
COPY ./core/config.docker.yaml /opt/ratings/core/config.yaml

WORKDIR /opt/ratings
ENV PYTHONPATH /opt/ratings

EXPOSE 8080

CMD ["python3", "core/application.py"]