version: '3.1'

services:
  postgres:
    build:
      context: .
    environment:
      POSTGRES_PASSWORD: ratings
      POSTGRES_USER: ratings
      POSTGRES_DB: ratings_core
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 6432:5432
volumes:
  postgresdata: