version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ratings_core
      POSTGRES_USER: ratings
      POSTGRES_PASSWORD: ratings
    ports:
      - "5432:5432"
