name: Publish Docker images

on:
  push:
    branches:    
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push core
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-core
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ratings_core:latest
      - name: Build and push webapp
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-webapp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ratings_webapp:latest
      - name: Build and push storage
        uses: docker/build-push-action@v2
        with:
          context: ./storage
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ratings_storage:latest